---
  - name: Install prerequisites
    apt:
      name:
        - default-jre
        - apt-transport-https
        - curl
        - software-properties-common
      state: present
    become: yes

  - name: Add ElasticSearch APT Repository key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    become: yes

  - name: Add ElasticSearh APT Repository
    apt_repository:
      repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
      state: present
    become: yes

  - name: Enable and Start ElasticSearch service
    systemd:
      name: elasticsearch
      enabled: yes
      state: started
    become: yes

  - name: Install Kibana
    apt:
      name: kibana
      state: present
    become: yes


  - name: Enable and start Logstash service
    systemd:
      name: logstash
      enabled: yes
      state: started
    become: yes

  - name: Restart ElasticSearch and Kibana
    systemd:
      name: "{{ item }}"
      state: restarted
    loop:
      - elasticsearch
      - kibana
