---
  - name: Enable and start ElasticSearch service
    service:
      name: elasticsearch
      enabled: yes
      state: started

  - name: Enable and start Kibana Service
    service:
      name: kibana
      enabled: true
      state: restarted

  - name: Enable and Start Logstash service
    service:
      name: logstash
      enabled: yes
      state: started
